// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8qGIrN7bNXrgqZll1WcNKtLUCR8b92_Y',
    appId: '1:184510523256:web:8d59d7fa09b9a8267bca8d',
    messagingSenderId: '184510523256',
    projectId: 'flutter-ggnz-67207',
    authDomain: 'flutter-ggnz-67207.firebaseapp.com',
    storageBucket: 'flutter-ggnz-67207.appspot.com',
    measurementId: 'G-0JN61K36SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs2PVctXKYsNMflEnwZnXcKk4FO7R45MA',
    appId: '1:184510523256:android:7ce221f5b1dcce347bca8d',
    messagingSenderId: '184510523256',
    projectId: 'flutter-ggnz-67207',
    storageBucket: 'flutter-ggnz-67207.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19-tKb4ifVlYr6WRdLx8BUgLqH6sds-4',
    appId: '1:184510523256:ios:2ff0d4081082a7477bca8d',
    messagingSenderId: '184510523256',
    projectId: 'flutter-ggnz-67207',
    storageBucket: 'flutter-ggnz-67207.appspot.com',
    iosBundleId: 'com.neeznggnz.tadpolediary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19-tKb4ifVlYr6WRdLx8BUgLqH6sds-4',
    appId: '1:184510523256:ios:2ff0d4081082a7477bca8d',
    messagingSenderId: '184510523256',
    projectId: 'flutter-ggnz-67207',
    storageBucket: 'flutter-ggnz-67207.appspot.com',
    iosBundleId: 'com.neeznggnz.tadpolediary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8qGIrN7bNXrgqZll1WcNKtLUCR8b92_Y',
    appId: '1:184510523256:web:7e20d8be60d6ec447bca8d',
    messagingSenderId: '184510523256',
    projectId: 'flutter-ggnz-67207',
    authDomain: 'flutter-ggnz-67207.firebaseapp.com',
    storageBucket: 'flutter-ggnz-67207.appspot.com',
    measurementId: 'G-0T70NR31FG',
  );

}